spring:
  application:
    name: api-gateway

  #api gateway config
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=2
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
              filters:
                - StripPrefix=2


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #URL of the Eureka Server where the client should register
      fetch-registry: true  #(usually true for clients)
      register-with-eureka: true #(usually true for clients)
  instance:
    prefer-ip-address: true #User IP instead of hostname for registration(useful for containers)
    lease-removal-interval-in-seconds: 10 #(default is 30)
    lease-expiration-duration-in-seconds: 30 #(default is 90) (edited)



